version: '3.7'

services:
  relayer:
    build:
      context: .
      target: relayer
    ports:
      - 3000:3000

  cli:
    build:
      context: .
      target: cli
    volumes:
      - ./zp-cli/client.config.js:/app/zp-cli/client.config.js
